### PR TITLE
Issue/15 Implements vertical/horizontal paginated loading + error/loading state handling + refactorings and fixes

### LINKED ISSUE #15: Carousel progress loading and error states
Jubako should support loading indicators and error-retry states at the end of loading carousels

### PR DESCRIPTION
**Pull request by fluxtah**
Fixes #15 and #13 Introduces paginated loading. See `GridFillActivity` for working example.

Includes many bug fixes and refactorings

### CODE REVIEW

File: jubako/src/main/java/com/justeat/jubako/ContentAdapterContentDescriptionCollectionListener.kt [hunk 1]
```diff
@@ -10,8 +10,8 @@ class ContentAdapterContentDescriptionCollectionListener(
     }
 
     override fun notifyItemInserted(index: Int) {
-        logger.log(TAG, "Notify Item Inserted", "index: $index")
-        contentAdapter.notifyItemInserted(index)
+        // logger.log(TAG, "Notify Item Inserted", "index: $index")
```
Comment (Electryc) [inline jubako/src/main/java/com/justeat/jubako/ContentAdapterContentDescriptionCollectionListener.kt]: Intentionally commented out ? Should you just remove ?

File: jubako/src/main/java/com/justeat/jubako/ContentAdapterContentDescriptionCollectionListener.kt [hunk 2]
```diff
@@ -25,11 +25,11 @@ class ContentAdapterContentDescriptionCollectionListener(
     }
 
     override fun notifyItemRangeInserted(positionStart: Int, itemCount: Int) {
-        logger.log(TAG,
-            "Notify Item Range Inserted",
-            "positionStart: $positionStart, itemCount: $itemCount"
-        )
-        contentAdapter.notifyItemRangeInserted(positionStart, itemCount)
+//        logger.log(TAG,
```
Comment (Electryc) [inline jubako/src/main/java/com/justeat/jubako/ContentAdapterContentDescriptionCollectionListener.kt]: Same comment as above

File: jubako/src/main/java/com/justeat/jubako/ContentDescriptionCollection.kt [hunk 3]
```diff
@@ -6,7 +6,7 @@ package com.justeat.jubako
  */
 class ContentDescriptionCollection(var listener: Listener? = null) {
 
-    private val mContentDescriptions = mutableListOf<ContentDescription<*>>()
+    internal var mContentDescriptions = mutableListOf<ContentDescription<*>>()
```
Comment (Electryc) [inline jubako/src/main/java/com/justeat/jubako/ContentDescriptionCollection.kt]: Should this be `contentDescriptions` without the Hungarian notation?

File: jubako/src/main/java/com/justeat/jubako/ContentDescriptionCollection.kt [hunk 4]
```diff
@@ -31,17 +31,10 @@ class ContentDescriptionCollection(var listener: Listener? = null) {
     fun clear() {
         val size = mContentDescriptions.size
         mContentDescriptions.clear()
+        mContentDescriptions = mutableListOf()
```
Comment (Electryc) [inline jubako/src/main/java/com/justeat/jubako/ContentDescriptionCollection.kt]: As we `clear` above, why do we need a new instance ?

File: jubako/src/main/java/com/justeat/jubako/JubakoAdapter.kt [hunk 5]
```diff
@@ -1,113 +1,48 @@
...
-    }
-
-    private fun canLoadMoreDescriptions(hasMore: Boolean, lastPos: Int, lastTimeVisibleItemPos: Int) =
-        hasMore && lastPos != lastTimeVisibleItemPos
-
-    override fun getItemCount(): Int {
-        return data.numItemsLoaded()
+    override fun init(recyclerView: RecyclerView) {
+        load()
+        (recyclerView as JubakoRecyclerView).onDrawComplete = {} // TODO why?
```
Comment (Electryc) [inline jubako/src/main/java/com/justeat/jubako/JubakoAdapter.kt]: _Why_ indeed 😆

File: jubako/src/main/java/com/justeat/jubako/JubakoAdapter.kt [hunk 6]
```diff
@@ -118,17 +53,20 @@ open class JubakoAdapter(
...
-
-        holder.onClickDelegate = { postViewHolderEvent(Event.Click(item.id, it)) }
-
-        attachReloader(item, holder)
+    override fun getItemCountActual(): Int = data.numItemsLoaded()
+    override fun getCurrentState(): PaginatedDataState<*> = state
+    override fun loadMore() = load()
+    override fun hasMoreToLoad(): Boolean {
+        return hasMore
+    }
```
Comment (Electryc) [inline jubako/src/main/java/com/justeat/jubako/JubakoAdapter.kt]: Can this be just:
```
override fun hasMoreToLoad() = hasMore
```

File: jubako/src/main/java/com/justeat/jubako/JubakoAdapter.kt [hunk 7]
```diff
@@ -118,17 +53,20 @@ open class JubakoAdapter(
...
 
-        bindWhenNewOrDefault(item, holder)
+    override fun getItem(position: Int): Any = data.getItem(position)
 
+    override fun bindItemToHolder(holder: JubakoViewHolder<Any>, item: Any) {
+        val description = (item as ContentDescription<Any>)
```
Comment (Electryc) [inline jubako/src/main/java/com/justeat/jubako/JubakoAdapter.kt]: Why not defining in the function param as `item: ContentDescription<Any>` then ?

File: jubako/src/main/java/com/justeat/jubako/PaginatedContentLoadingStrategy.kt [hunk 8]
```diff
@@ -30,19 +31,30 @@ open class PaginatedContentLoadingStrategy(private val pageSize: Int = DEFAULT_P
...
         lifecycleOwner: LifecycleOwner,
         data: Jubako.Data,
-        onLoaded: (hasMore: Boolean) -> Boolean
+        callback: (state: PaginatedDataState<ContentDescription<Any>>, hasMore: Boolean) -> Unit
     ) {
         logger.log(TAG, "Load", "onReload: $reset, loading observers: ${loadingData.size}")
-        if (BuildConfig.DEBUG) {
-            TEMP_integrityCheck(data.source, data.destination)
-        }
+//        if (BuildConfig.DEBUG) {
```
Comment (Electryc) [inline jubako/src/main/java/com/justeat/jubako/PaginatedContentLoadingStrategy.kt]: Needed ? Should it be deleted ?

File: jubako/src/main/java/com/justeat/jubako/ContentAdapterContentDescriptionCollectionListener.kt (hunk 1 above)
Comment (fluxtah) [reply jubako/src/main/java/com/justeat/jubako/ContentAdapterContentDescriptionCollectionListener.kt]: @Electryc thanks man yeh I think all these notify functions are now redundant now progress loading is all handled by `ProgressAdapter`

File: jubako/src/main/java/com/justeat/jubako/ContentDescriptionCollection.kt (hunk 3 above)
Comment (fluxtah) [reply jubako/src/main/java/com/justeat/jubako/ContentDescriptionCollection.kt]: @Electryc yeh, overspill from legacy java! thanks

File: jubako/src/main/java/com/justeat/jubako/ContentDescriptionCollection.kt (hunk 4 above)
Comment (fluxtah) [reply jubako/src/main/java/com/justeat/jubako/ContentDescriptionCollection.kt]: its a good question it was to remove the association from the old list instead of working on the same cleared list since it was being consumed by an adapter, this whole collection business needs a rethink and not sure if I did this to solve a bug, will revisit later.

File: jubako/src/main/java/com/justeat/jubako/JubakoAdapter.kt (hunk 6 above)
Comment (fluxtah) [reply jubako/src/main/java/com/justeat/jubako/JubakoAdapter.kt]: yep

File: jubako/src/main/java/com/justeat/jubako/JubakoAdapter.kt (hunk 7 above)
Comment (fluxtah) [reply jubako/src/main/java/com/justeat/jubako/JubakoAdapter.kt]: Very good catch @Electryc was an oversight since the generic data type was specified as `Any` and not `ContentDescription<Any>`!

File: jubako/src/main/java/com/justeat/jubako/PaginatedContentLoadingStrategy.kt (hunk 8 above)
Comment (fluxtah) [reply jubako/src/main/java/com/justeat/jubako/PaginatedContentLoadingStrategy.kt]: not sure, it was a sanity check and was quite useful I think is worth keeping till this guy has a unit test that can confirm the same thing, still think the design of Jubako needs some work though so maybe after that! :)
